### PR TITLE
Upgrade to Cython 3 and pyarrow 13.0.0

### LINKED ISSUE #43: Support manylinux_2_28 builds
manylinux2014 will be deprecated in July 2014 and arrow may start supporting manylinux_2_28 soon:

- https://github.com/apache/arrow/pull/34818

It'd also  be useful to support `_GLIBCXX_USE_CXX11_ABI=1` for  source builds on other systems

- https://github.com/ratt-ru/arcae/issues/29#issuecomment-1623235078

This would involve:

- Creating a new vcpkg triplet `x64-linux-dynamic-cxx17-abi1-rel` based on the existing ABI0 triplet https://github.com/ratt-ru/arcae/blob/ac315e95f9dccd2441a07709327b8671fb26abd3/vcpkg/overlay-triplets/x64-linux-dynamic-cxx17-abi0-rel.cmake#L11
- Setting the ABI here: https://github.com/ratt-ru/arcae/blob/ac315e95f9dccd2441a07709327b8671fb26abd3/cpp/CMakeLists.txt#L15
- and here: https://github.com/ratt-ru/arcae/blob/ac315e95f9dccd2441a07709327b8671fb26abd3/arcae/CMakeLists.txt#L15
- Configuring cmake appropriately based on the desired ABI
- Configuring cibuildwheel to build in a manylinux_2_28 docker container

### LINKED ISSUE #47: Update build to use pyarrow 13.0.0 and Cython 3.0

### PR DESCRIPTION
**Pull request by sjperkins**
- Closes #47 
- Closes #43

### CODE REVIEW

**Comment by sjperkins** [comment]
@orliac just a heads up that I'm changing the C++ ABI from `GLIBCXX_USE_CXX11_ABI=0` to `GLIBCXX_USE_CXX11_ABI=1` in this PR. I know you changed your SPAC build to use the older ABI. Previous discussion here:

- https://github.com/ratt-ru/arcae/issues/29#issuecomment-1632333160

 I would've preferred to continue with the older ABI and there isn't a problem with the wheels built with it. However, one difficulty is that `pyarrow 13.0.0` releases both `manylinux2014` (old ABI) and `manylinux_2_28` (new ABI) wheels, and pip prefers to install the newer one by default, causing symbol incompatibilities with a `manylinux2014` arcae wheel.

My intention here is to bite the bullet and configure arcae to build `manylinux_2_28` only. This should be fine as `pip >= 20.3` supports `manylinux_x_y` tags and was released in Nov 30 2020.

However, perhaps there's another way around the above issue? Let me know if you can see something I can't!

**Comment by sjperkins** [comment]
I'm intending to merge this PR soon.

**Comment by orliac** [comment]
Hi @sjperkins,
Thanks for the update. Once you've merged I will update my Spack stack accordingly and let you know about the outcome. But the move makes sense to me.

**Comment by sjperkins** [comment]
Thanks, also looks like Centos 7, on which `manylinux2014` is based, will reach [EOL](https://peps.python.org/pep-0599/#rationale) in 9 months:

> Similar to how [PEP 571](https://peps.python.org/pep-0571/) and [PEP 513](https://peps.python.org/pep-0513/) drew allowed shared libraries and their symbol versions from CentOS 5.11 and CentOS 6, respectively, a manylinux2014 platform tag will draw its libraries and symbol versions from CentOS 7, which will reach end-of-life on June 30th, 2024. [[1]](https://peps.python.org/pep-0599/#id8)

**Pull request merged**
